### ISSUE TITLE
हिष्ठान्तः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#10]
Input word is - बंहिष्ठः
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By phiṣo'nta udāttaḥ (phi-1) :
फिषोऽन्त उदात्तः (फि-१) :
1 - बंहिष्ठ॑ः
हिष्ठवत्सरतिशत्थान्तानाम् इति सूत्रेण अन्त उदात्तः भवेत्।

**Comment by mrudani** [comment]
बंहिष्ठ इति दत्ते सति हिष्ठत्सरतिशत्थान्तानाम् इति दर्शयति। यज्यते प्रयासः।

**Comment by drdhaval2785** [comment]
Right now we are not dealing with subanta forms.
Only base forms are given accents.

2015-09-10 21:15 GMT+05:30 mrudani notifications@github.com:

> बंहिष्ठ इति दत्ते सति हिष्ठत्सरतिशत्थान्तानाम् इति दर्शयति। यज्यते प्रयासः।
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drdhaval2785/SanskritAccent/issues/10#issuecomment-139286580
> .

## 

Dr. Dhaval Patel, I.A.S
Collector and District Magistrate, Anand
www.sanskritworld.in
