### ISSUE TITLE
कृष्ण - नामवाचि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#13]
Input word is - कृष्ण
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - कृष्ण
By varṇānāṃ taṇatinitāntānām (phi-33) :
वर्णानां तणतिनितान्तानाम् (फि-३३) :
1 - कृ॑ष्ण

वा नामधेयस्य इति सूत्रेण अन्त उदात्तः भवति विकल्पेन। पक्षे आदिरुदात्तः।

**Comment by drdhaval2785** [comment]
For Candas, this is implemented.
