### ISSUE TITLE
गौर

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#15]
Input word is - गौर
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - गौर
By laghāvante dvayośca bahvaṣo guruḥ (phi-42) :
लघावन्ते द्वयोश्च बह्वषो गुरुः (फि-४२) :
1 - गौ॑र
शुक्लगैरयोरादिः इति सूत्रेण आदिरुदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
As per svarasiddhAntacandrikA, the rule has anuvRtti of 'vA'. Therefore, 'zuklagaurayorAdiH' is shown as optionally applicable.
