### ISSUE TITLE
अङ्गुष्ठ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#16]
Input word is - अङ्गुष्ठ
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By aṅguṣṭhodakabakavaśānāṃ chandasyantaḥ (phi-14) :
अङ्गुष्ठोदकबकवशानां छन्दस्यन्तः (फि-१४) :
1 - अङ्गुष्ठ॑
स्वाङ्गानामकुर्वादीनाम् इति सूत्रेण द्वितीयस्य उदात्तः प्राप्तः तं प्रबाध्य अनेन सूत्रेण अन्तः उदात्तः।

**Comment by drdhaval2785** [comment]
As noted in earlier threads, it would be difficult to show pratiSedha or paryudAsa in current scheme.
Not possible right now. Will see later on.
