### ISSUE TITLE
वश

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#19]
Input word is - वश
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By phiṣo'nta udāttaḥ (phi-1) :
फिषोऽन्त उदात्तः (फि-१) :
1 - वश॑
अङ्गुष्ठोदक.. इत्यादिसूत्रेण अन्त उदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
Did u click the vaidika ?

**Comment by mrudani** [comment]
एवम्। तदेव चितम्।

**Comment by drdhaval2785** [comment]
I had kept 'vaSA' only earlier. Now I have added 'vaSa'.
