### ISSUE TITLE
पृष्ठ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#20]
Input word is - पृष्ठ
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By pṛṣṭhasya ca (phi-15) :
पृष्ठस्य च (फि-१५) :
1 - पृष्ठ॑

स्वाङगशिटामदन्तानाम् इति आद्युदात्ते प्राप्ते अनेन अन्त उदात्तः।

**Comment by mrudani** [comment]
Input word is - पृष्ठ
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By pṛṣṭhasya ca (phi-15) :
पृष्ठस्य च (फि-१५) :
1 - पृ॑ष्ठ
2 - पृष्ठ॑
भाषायाम् वा अन्तोदात्तः भवति। वा भाषायाम् इति सूत्रेण।

**Comment by drdhaval2785** [comment]
Only svarasiddhAntacandrikA has 'vA bhASAyAm' sUtra.
All other readings have this in 'pRSThasya ca'.

**Comment by mrudani** [comment]
तर्हि वा भाषायाम् इति सूत्रमनपेक्षितमिति अभिप्रायो वा।

**Comment by drdhaval2785** [comment]
No. All I want to say is - check the usage. If the usage has this svara, we shall incorporate it. Otherwise, we will ignore 'vA bhASAyAm' sUtra.

**Comment by mrudani** [comment]
तथैव क्रियताम्.

**Comment by drdhaval2785** [comment]
Right now added this sUtra as a subsidiary sUtra फि-१५-१. Just like vArtikas for AS sUtras.
