### ISSUE TITLE
अर्जुन - तृणाख्या

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#21]
Input word is - अर्जुन
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - अर्जुन
By unarvannantānām (phi-32) :
उनर्वन्नन्तानाम् (फि-३२) :
1 - अर्जु॑न

अर्जुनशब्दस्य तृणाख्यायां उनर्वन्न्तानाम् इति सूत्रेण प्राप्तमाद्युदात्तं बाधित्वा अर्जुनस्य तृणाख्यायाम् इति सूत्रेण अन्त उदात्तः भवेत्। वृक्ष इत्यर्थे तु आद्युदात्त एव।

**Comment by drdhaval2785** [comment]
It happens. Nothing remained to be done.
