### ISSUE TITLE
माँस

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#31]
Input word is - मनस्
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - मनस्
By nabviṣayasyānisantasya (phi-26) :
नब्विषयस्यानिसन्तस्य (फि-२६) :
1 - म॑नस्

मनस् शब्दस्तु अन्तोदात्त एव, मनेर्दीर्घश्च इति सप्रत्ययान्तत्वात् इति कर्मण्यण् इत्यत्र कैयटः।

**Comment by drdhaval2785** [comment]
![10-9-2015 6-07-20 pm](https://cloud.githubusercontent.com/assets/5755132/10393800/9ed066e2-6eb0-11e5-8e4f-557ffdf4a0bd.png)
@mrudani 
What I understand is that 'mAsa' gets antodAttatva according to this text, and not 'manas'.
Correct me if I am wrong.

**Comment by mrudani** [comment]
क्षन्तव्या। माँस इति सेखनीये मनस् इति लिखितम्। माँसशब्दस्य अन्तोदात्तः इति।
