### ISSUE TITLE
मुद्ग

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#33]
Input word is - मुद्ग
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - मुद्ग
By tṛṇadhānyānāṃ ca dvyaṣām (phi-27) :
तृणधान्यानां च द्व्यषाम् (फि-२७) :
1 - मु॑द्ग

मुद्गशब्दस्य घृतादित्वं वदति हरदत्तः, तस्मात् अन्त उदात्तः।

**Comment by drdhaval2785** [comment]
Reference or image please

**Comment by mrudani** [comment]
बिल्वादिभ्योण् इत्यत्र हरदत्तः इति स्वरसिद्धान्तचन्द्रिका।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/10716117/2f7836f2-7b54-11e5-89f6-47cb18363a02.PNG)
All three issues settled #34, #38 also settled.
