### ISSUE TITLE
 व्रीहि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#34]
Input word is - व्रीहि
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - व्रीहि
By igantānāṃ ca dvyaṣām (phi-49) :
इगन्तानां च द्व्यषाम् (फि-४९) :
1 - व्रीहि॑
2 - व्री॑हि

व्रीहिशब्दस्य घृतादित्वं हरदत्तेनोक्तत्वात् अन्त उदात्तः।

**Comment by drdhaval2785** [comment]
Reference please.
Where did haradatta say so ?

**Comment by mrudani** [comment]
इति स्वरसिद्धान्तचन्द्रिकाकारः। कु्वेति अन्वेष्टव्यम्।

**Comment by mrudani** [comment]
बिल्वादिभ्योण् इति सूत्रे हरदत्तः इति स्वरसिद्धान्तचन्द्रिका।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritAccent/commit/8dfda7f08b2bbce5c1cb66dfc12e2ecde209eadb closes the issue
