### ISSUE TITLE
अन्य

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#38]
Input word is - अन्य
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - अन्य
By atha dvitīyaṃ prāgīṣāt (phi-50) :
अथ द्वितीयं प्रागीषात् (फि-५०) :
1 - अन्य
By yāntasyāntyātpūrvam (phi-62) :
यान्तस्यान्त्यात्पूर्वम् (फि-६२) :
1 - अ॑न्य

अन्यशब्दे अन्तोदात्तत्वमिति स्वाङ्गशिटामदन्तानाम् इति सूत्रव्याख्यायं वर्तते।

**Comment by drdhaval2785** [comment]
![10-9-2015 5-52-44 pm](https://cloud.githubusercontent.com/assets/5755132/10393565/9cc271b2-6eae-11e5-914a-266d6e0924ac.png)

@mrudani 
I am finding it difficult to understand.
The author writes उभयशब्दे तु परत्वात्‌ 'यान्तस्यान्त्यात्‌ पूर्वम्‌' इति स्वरः । i.e. uBa^ya.
Whereas he once again writes 'उभयशब्दवत्‌ अन्यशब्देऽन्तोदात्तत्वम्‌'.

How do these two statements go together. The first sentence says it is 'antyAtpUrvam' and the second statement says it is 'antodAtta'.

Please clarify.

**Comment by mrudani** [comment]
सर्वोभान्यशब्दाः गणे अन्तोदात्ताः निपात्यन्ते। इति शेखरकाराः। तस्मात् अन्तोदात्तः एव भवतु।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritAccent/commit/8dfda7f08b2bbce5c1cb66dfc12e2ecde209eadb closed this issue
