### ISSUE TITLE
नकुल

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#39]
Input word is - नकुल
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - नकुल
By hayādīnāmasaṃyuktalāntānāmantaḥ pūrvaṃ vā (phi-48) :
हयादीनामसंयुक्तलान्तानामन्तः पूर्वं वा (फि-४८) :
1 - नकुल॑
2 - नकु॑ल

नकुलशब्दस्य प्राणिवाचिकत्वात् प्राणिनां कुपूर्वम् इति सूत्रेण कवर्गात् पूर्व आदिरुदात्तः भवेत्। परन्तु सः स्वरः प्रयोगेषु न दृश्यते इति व्याख्यातारः। तथापि हयादीनामसंयुक्त इत्यादिसूत्रेण विधीयमानः स्वरः विकल्पेन आदेः, अन्तस्य, तत्पूर्वस्य वा भवेत्।

**Comment by drdhaval2785** [comment]
Corrected to three svaras

```
1 - न॑कुल

2 - नकुल॑

3 - नकु॑ल
```
