### ISSUE TITLE
avyaya is not separate tab

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#4]
उच्चैस्, नीचैस् इति अव्ययौ स्तः। परन्तु तत्र पुंलिङ्गस्त्रीलिङ्गनपुंसकलिङ्गन् एव दर्शयति।

**Comment by drdhaval2785** [comment]
@mrudani what would be the applicable rule ?

**Comment by mrudani** [comment]
फिषो अन्त उदात्तः

**Comment by drdhaval2785** [comment]
I don't see much utility by adding this avyaya as separate category in addtion to m,f,n.

If you choose m/f/n anything with uccEs, the output is proper.
Therefore, I will just keep this issue for documentation and close it.
