### ISSUE TITLE
पुरुष

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#47]
Input word is - पुरुष

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By phiṣo'nta udāttaḥ (phi-1) :

फिषोऽन्त उदात्तः (फि-१) :

1 - पुरुष॑

ग्रामादीनां च इति सूत्रेण आदिः उदात्तः।

**Comment by drdhaval2785** [comment]
puruza was misspelled as purUza.
Corrected
