### ISSUE TITLE
स्फिगन्तस्य....

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#48]
स्फिगन्तस्योपेमयनामधेयस्य इअति सूत्रस्य प्रवृत्तिः कथम परीक्षणीया। 
चञ्चेव चञ्चा - चञ्चा इति भवति। अत्र किं परीक्षणीयमिति मे संशयः।

**Comment by mrudani** [comment]
तथैव न वृक्षपर्वतविशेषव्याघ्रसिंहमहिषाणाम् इति सूत्रप्रवृत्तिपरीक्षणे अपि क्लेशः।

**Comment by drdhaval2785** [comment]
This is the comment I had made in the code

```
// Check whether the interpretation is correct or not. It seems that 39,40 are not word specific. They are context dependent.
```

Currently, I have kept both as default.
e.g. caYcA / meru etc give their sUtras

**Comment by drdhaval2785** [comment]
Related to #1
