### ISSUE TITLE
केकय

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#52]
Input word is - केकय

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - केकय

By atha dvitīyaṃ prāgīṣāt (phi-50) :

अथ द्वितीयं प्रागीषात् (फि-५०) :

1 - केकय

By yāntasyāntyātpūrvam (phi-62) :

यान्तस्यान्त्यात्पूर्वम् (फि-६२) :

1 - केक॑य

जनपदशब्दानामषन्तानाम् इति सूत्रेण आदिरुदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
@mrudani Can you provide a complete (or at least commonly used) janapada names ?

**Comment by drdhaval2785** [comment]
This question is deliberated and treated in #80.
No need to keep this issue open now.
