### ISSUE TITLE
वदन

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#55]
Input word is - वदन

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - वदन

By nabviṣayasyānisantasya (phi-26) :

नब्विषयस्यानिसन्तस्य (फि-२६) :

1 - व॑दन

वदनशब्दस्य स्वाङ्गशिटामदन्तानाम् इति सूत्रेण आदिरुदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
Great.
![10-14-2015 8-37-19 pm](https://cloud.githubusercontent.com/assets/5755132/10487800/6583d5ca-72b3-11e5-9434-1240bb5794e4.png)

This entry in svarasiddhAntacandrika sUtra svAGgakurvAdInAm clarifies that even in tryacAm, svAGgAnAmakurvAdInAm (52) doesn't apply, and 'svAGgaziTAmadantAnAm' applies.
