### ISSUE TITLE
मलय

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#56]
Input word is - मलय

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - मलय

By atha dvitīyaṃ prāgīṣāt (phi-50) :

अथ द्वितीयं प्रागीषात् (फि-५०) :

1 - मलय

By tryacāṃ prāṅmakarāt (phi-51) :

त्र्यचां प्राङ्मकरात् (फि-५१) :

1 - मलय

By mādīnāṃ ca (phi-53) :

मादीनां च (फि-५३) :

1 - मल॑य

अत्र अथादिः प्राक् शकटेः इति सूत्रस्य आवश्यकतैव नास्ति।

**Comment by drdhaval2785** [comment]
Same as mentioned earlier in #58
