### ISSUE TITLE
शीतला

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#58]
Input word is - शीतला

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - शीतला

By strīviṣayavarṇākṣupūrvāṇām (phi-43) :

स्त्रीविषयवर्णाक्षुपूर्वाणाम् (फि-४३) :

1 - शी॑तला
अथादिः प्राक् शकटेः इति सूत्रस्य आवश्यकता नास्ति। स्त्रीविषयवर्णाक्षुपूर्वाणाम् इति सूत्रस्य न प्रवृत्तिः। सादीनां शाकानाम् इति सूत्रेण द्वितीयमुदात्तम्।

**Comment by drdhaval2785** [comment]
I agree that it has to be covered under `सादीनां शाकानाम्`.
But, I disagree on point that अथादिः प्राक्‌ शकटेः is not needed.
Reasons
1. अथादिः प्राक्‌ शकटेः adhikAra runs till शकटिशकट्यो.. (६९)
2. अथ द्वितीयं प्रागीषात्‌ adhikAra runs till ईषान्तस्य हयादेरादिर्वा (६६)
3. त्र्यचां प्राङ्मकरात् adhikAra runs till मकरवरू... (५७).

As सादीनां शाकानाम्‌ falls at 54, all these three adhikAras are running and required to be displayed.
