### ISSUE TITLE
कुणप

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#59]
Input word is - कुणप

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By phiṣo'nta udāttaḥ (phi-1) :

फिषोऽन्त उदात्तः (फि-१) :

1 - कुणप॑

छन्दसि च इति सूत्रेण द्वितीयमुदात्तम्।

**Comment by drdhaval2785** [comment]
Where is it given ?
I have three books

1 .zAntanava's phiTsUtras with laghuzabdenduzekhara

![10-14-2015 5-44-09 pm](https://cloud.githubusercontent.com/assets/5755132/10483137/331e8a5c-729b-11e5-868f-30868f217075.png)
1. svarasiddhAntacandrikA
   ![10-14-2015 5-44-52 pm](https://cloud.githubusercontent.com/assets/5755132/10483148/4e46617e-729b-11e5-8809-48ef9a3159b2.png)
2. siddhAntakaumudI with subodhinI vyAkhyA
   ![10-14-2015 5-45-33 pm](https://cloud.githubusercontent.com/assets/5755132/10483162/6a734024-729b-11e5-895e-329b1d4c83b8.png)

I am not able to get exact reference to `कुणप`.

**Comment by mrudani** [comment]
पान्तानां गुर्वादीनामिति सूत्रव्याख्याने स्वरसिद्धान्तचन्द्रिकायां वर्तते.

**Comment by drdhaval2785** [comment]
There are two छन्दसि च (10 and 58).
Kept 58. It is open ended. 10 is only for 'dakziRa'.
