### ISSUE TITLE
गुद स्त्रियाम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#6]
Input word is - गुद
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By gudasya ca (phi-4) :
गुदस्य च (फि-४) :
1 - गुद॑

गुदशब्दः स्त्रियाम् स्वाङ्गशिटामदन्तानाम् इति सूत्रेण आदिरुदात्तः भवति।

**Comment by drdhaval2785** [comment]
feminine has 'gudA'. The output has 'svAGga....' in case input is 'gudA'.
Should we take 'guda' as an input @mrudani ?

**Comment by mrudani** [comment]
स्वाङ्गशिटामदन्तानाम् इति सूत्रस्य प्रवृत्तिः अदन्तेष्वेव भवतीति कारणेन गुद इत्येव देयम्.
