### ISSUE TITLE
वरूथ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#60]
Input word is - वरूथ

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By baṃhiṣṭhavatsaratiśatthāntānām (phi-7) :

बंहिष्ठवत्सरतिशत्थान्तानाम् (फि-७) :

1 - वरूथ॑

मकरवरूथपारेवतवित.... इतियादिना आदिः, द्वितीयो वा उदात्तः।

**Comment by drdhaval2785** [comment]
Some books had 'varUTa'. Some had 'varUQa'.
Added both now.
