### ISSUE TITLE
उदकम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#61]
Input word is - उदक

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By aṅguṣṭhodakabakavaśānāṃ chandasyantaḥ (phi-14) :

अङ्गुष्ठोदकबकवशानां छन्दस्यन्तः (फि-१४) :

1 - उदक॑

कर्दमादीनां च इति सूत्रेण आदिर्द्वितीयो वा उदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
It seems that you hava 'vaidika' selected.
If you select 'laukika' - it gives kardamAdInAM ca
