### ISSUE TITLE
तेजन

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#62]
Input word is - तेजन

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - तेजन

By laghāvante dvayośca bahvaṣo guruḥ (phi-42) :

लघावन्ते द्वयोश्च बह्वषो गुरुः (फि-४२) :

1 - ते॑जन

सुगन्धितेजनस्य ते वा इति सूत्रेण आदिर्द्वितीयः उदात्तः, तेशब्दश्च उदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
![10-13-2015 8-06-13 pm](https://cloud.githubusercontent.com/assets/5755132/10457923/f011be92-71e5-11e5-8c5c-77cfc1b50297.png)

From example, it is clear that this rule is not for 'sugandhi' and 'tejana' separately, but totally for 'sugandhitejana' as compound.
