### ISSUE TITLE
सनाथा

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#64]
Input word is - सनाथा

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - सनाथा

By atha dvitīyaṃ prāgīṣāt (phi-50) :

अथ द्वितीयं प्रागीषात् (फि-५०) :

1 - सनाथा

By thāntasya ca nālaghunī (phi-63) :

थान्तस्य च नालघुनी (फि-६३) :

1 - सना॑था

आन्तस्य नालघुनी इति सूत्रमस्ति स्वरसिद्धान्तकौमुद्याम्।

**Comment by drdhaval2785** [comment]
[Phit-Sutra-s from Siddhanta Kaumudi with Skt Commentary Subodhini -  Pansikar 1908.pdf](https://github.com/drdhaval2785/SanskritAccent/files/12495/Phit-Sutra-s.from.Siddhanta.Kaumudi.with.Skt.Commentary.Subodhini.-.Pansikar.1908.pdf)

The above book has the following commentary -
`केचित्तु आन्तस्य च नालघुनी इति पठित्वा आकारान्तस्य नाशब्दस्य च लघुनी अन्त्यात्पूर्व उदात्ते स्त इति व्याख्याय नान दिवा मुधा इत्युदाजह्रुः ।`

Thus it seems that the base reading is 'thAntasya' and some read it as 'Antasya'.

Whatever is your suggestion, let me know.

**Comment by mrudani** [comment]
आन्तस्य नालघुनी इति सूत्रेण बहुलक्ष्यसाधनं भवतीति हेतुना तथैव भवतु.

**Comment by drdhaval2785** [comment]
Antasya nAlaghunI kept.
