### ISSUE TITLE
साङ्काश्य

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#65]
Input word is - साङ्काश्य

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - साङ्काश्य

By atha dvitīyaṃ prāgīṣāt (phi-50) :

अथ द्वितीयं प्रागीषात् (फि-५०) :

1 - साङ्काश्य

By sāṅkāśyakāmpilyanāsikyadārvāghāṭānām (phi-65) :

साङ्काश्यकाम्पिल्यनासिक्यदार्वाघाटानाम् (फि-६५) :

1 - सा॑ङ्काश्य

2 - साङ्का॑श्य

अन्त्यात् पूर्वं द्वितीयं वा उदात्तमिति स्वरकौमुदीकारः।

**Comment by drdhaval2785** [comment]
साङ्काश्यशब्दे त्र्यज्वति अन्त्यात्पूर्वमेव द्वितीयः स्वरः । तर्हि कथं विकल्प इति प्रश्नः ।

**Comment by mrudani** [comment]
आद्युदात्तः न विधीयते खलु तर्हि कथमाद्युदात्त इति।

**Comment by drdhaval2785** [comment]
![10-13-2015 5-59-05 pm](https://cloud.githubusercontent.com/assets/5755132/10454691/2908dcb0-71d4-11e5-803b-21bfc283e6f6.png)

अत्र लघुशब्देन्दुशेखरे स्थितम्‌ ।
`मण्डूकप्लुत्या आदिर्वेति वर्तते ।`
तथैव
`अन्त्यात्पूर्वमिति तु नानुवर्तते साङ्काश्यादीनां त्रयाणां ग्रहणस्य वैयर्थ्यापत्तेः ।`

**Comment by mrudani** [comment]
एवं तर्हि साधु। मयि  लघुशब्देन्दुशेखरो न वर्तते। कृपया प्रेषयन्तु।

**Comment by drdhaval2785** [comment]
Sent a mail with book attached.
Closing the issue
