### ISSUE TITLE
शरीर

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#67]
Input word is - शरीर

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - शरीर

By nabviṣayasyānisantasya (phi-26) :

नब्विषयस्यानिसन्तस्य (फि-२६) :

1 - श॑रीर

उशीरदाशेरकपाल... इत्यादिना आदिरुदात्तो भवति।

**Comment by drdhaval2785** [comment]
It was misspelt as 'SArIra'. Corrected to 'SarIra'
