### ISSUE TITLE
आषाढ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#68]
Input word is - आषाढ

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - आषाढ

By laghāvante dvayośca bahvaṣo guruḥ (phi-42) :

लघावन्ते द्वयोश्च बह्वषो गुरुः (फि-४२) :

1 - आषा॑ढ

महिष्याषाढयोर्जायेष्टाख्या चेत् इति सूत्रेण आदिरुदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
It is not relevant to 'AzAQa'. It is relevant to 'azAQA' (अषाढा).
Not corrected.
See

![10-13-2015 8-03-36 pm](https://cloud.githubusercontent.com/assets/5755132/10457838/877affce-71e5-11e5-8643-77afc4cafac0.png)

**Comment by mrudani** [comment]
Input word is - अषाढ

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - अषाढ

By laghāvante dvayośca bahvaṣo guruḥ (phi-42) :

लघावन्ते द्वयोश्च बह्वषो गुरुः (फि-४२) :

1 - अषा॑ढ

**Comment by drdhaval2785** [comment]
Test अषाढा.
not अषाढ.
