### ISSUE TITLE
गोष्ठ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#69]
Input word is - गोष्ठ

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - गोष्ठ

By laghāvante dvayośca bahvaṣo guruḥ (phi-42) :

लघावन्ते द्वयोश्च बह्वषो गुरुः (फि-४२) :

1 - गो॑ष्ठ

गोष्ठजस्य ब्राह्मणनामधेयस्य इति सूत्रेण अक्षरमक्षरं पर्यायेणोदात्तं सिध्यति।

**Comment by drdhaval2785** [comment]
It seems that you tested with the wrong word `गोष्ठ`.
To me, it appears that the word qualifying for this sUtra is `गोष्ठज`
