### ISSUE TITLE
सुखम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#7]
By athādiḥ prāk śakaṭeḥ (phi-24) :
अथादिः प्राक् शकटेः (फि-२४) :
1 - सुखम्
By nabviṣayasyānisantasya (phi-26) :
नब्विषयस्यानिसन्तस्य (फि-२६) :
1 - सु॑खम्

खान्तस्याश्मादेः इति सूत्रेण अन्त उदात्तः भवति। नव्बिषयस्यानिसन्तस्य इति सूत्रं बाधित्वा एतत् प्रवर्तते।

**Comment by drdhaval2785** [comment]
Wonderful feedback. Please go ahead posting such corrections.
