### ISSUE TITLE
कालवाल

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#70]
Input word is - कालवाल

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By athādiḥ prāk śakaṭeḥ (phi-24) :

अथादिः प्राक् शकटेः (फि-२४) :

1 - कालवाल

By hayādīnāmasaṃyuktalāntānāmantaḥ pūrvaṃ vā (phi-48) :

हयादीनामसंयुक्तलान्तानामन्तः पूर्वं वा (फि-४८) :

1 - का॑लवाल

2 - कालवाल॑

3 - कालवा॑ल

धूम्रजानुमुञ्जकेशकालवाल... इत्यादिना लवर्जयित्वा अन्ये पर्यायेणोदात्ताः भवन्ति।

**Comment by drdhaval2785** [comment]
The issue was that the code had `"kAlavAla"."sTAlIpAka"` instead of `"kAlavAla","sTAlIpAka"` in the array.
So the machine understood it to be "kAlavAlasTAlIpAka" single word.
Funny, but painful
