### ISSUE TITLE
स्वरितचिह्नम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#72]
न्य᳠ङ्,
 स्व᳠र्,
 न्य᳠र्बुद,
व्य᳠ल्कश
स्वरितः न दृश्यते।

**Comment by drdhaval2785** [comment]
Download siddhanta font http://www.svayambhava.org/.
Whatever you messaged looks like this to me.
![10-14-2015 5-27-58 pm](https://cloud.githubusercontent.com/assets/5755132/10482817/f0da3152-7298-11e5-8efe-b713d477b622.png)

And our notice in the first line of output looks like 
![10-14-2015 5-28-43 pm](https://cloud.githubusercontent.com/assets/5755132/10482830/0eeaafbe-7299-11e5-8747-b238537c0225.png)

Thus we are showing in the output how we will display svarita.

Obviously, there are many conventions for denoting svarita. Some of them depend on the Veda branch you are studying.
Whatever convention you suggest, I will follow.

**Comment by mrudani** [comment]
नास्ति दोषः, परं मत्सविधे लिपेरभावात् तथा न दृश्यते स्म. उदात्ताय उपयुक्तः एव स्वरिताय उपयुनक्ति लोके अधिकाधिकतया, तथा सति उदात्तचिह्नमपि परिवर्तनीयमतः एवमेव भवतु, अथवा यत्स्वरिताय उपयुक्तं तत् उदात्ताय कर्तुं शक्यते.

**Comment by drdhaval2785** [comment]
एवमेव भवतु अधुना ।
