### ISSUE TITLE
बिल्व

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#73]
Input word is - बिल्व

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By bilvatiṣyayoḥ svarito vā (phi-23) :

बिल्वतिष्ययोः स्वरितो वा (फि-२३) :

1 - बिल्व॑

2 - बिल्व᳠

बिल्वभक्ष्यवीर्याणि छन्दसि इति सूत्रमपि वर्तते अन्तस्वरितविधायकम्।

**Comment by drdhaval2785** [comment]
Corrected.
In Chandas it is antasvarita.
In laukika it is optional antasvarita antodAtta.
