### ISSUE TITLE
सिम

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#75]
Input word is - सिम

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By tvattvasamasimetyanuccāni (phi-78) :

त्वत्त्वसमसिमेत्यनुच्चानि (फि-७८) :

1 - सिम॒
सर्वानुदात्तानि इति शेखरे।

**Comment by mrudani** [comment]
सिमस्याथर्वणे अन्त उदात्तः इति सूत्रेण वा अन्तोदात्तः भवेत्।

**Comment by drdhaval2785** [comment]
By tvattvasamasimetyanuccāni (phi-78) :

त्वत्त्वसमसिमेत्यनुच्चानि (फि-७८) :

1 - सि॒म॒

By simasyātharvaṇe'nta udāttaḥ (phi-79) :

सिमस्याथर्वणेऽन्त उदात्तः (फि-७९) :

1 - सि॒म॒

2 - सिम॑
