### ISSUE TITLE
यथा 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#78]
Input word is - यथा

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By yatheti pādānte (phi-85) :

यथेति पादान्ते (फि-८५) :

1 - यथा

2 - यथा॑

By nipātā ādyudāttāḥ (phi-80) :

निपाता आद्युदात्ताः (फि-८०) :

1 - य॑था

2 - य॑था॑

अन्तोदात्तः केन भवति। तथा च उभयोरुदात्तः कथम्।

**Comment by drdhaval2785** [comment]
By nipātā ādyudāttāḥ (phi-80) :

निपाता आद्युदात्ताः (फि-८०) :

1 - य॑था

By yatheti pādānte (phi-85) :

यथेति पादान्ते (फि-८५) :

1 - य॑था

2 - यथा॒
