### ISSUE TITLE
द्विरुक्तिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#79]
Input word is - पटुपटु

Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita

By prakārādidviruitau (phi-86) :

प्रकारादिद्विरुइतौ (फि-८६) :

1 - पटुपटु॑

सूत्रे दोषः इतौ इति वर्तते परिष्करणीयम्।

**Comment by drdhaval2785** [comment]
प्रकारादिद्विरुक्तौ परस्यान्त उदात्तः (फि-८६) :
