### ISSUE TITLE
अजँ लिट् सिप्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#85]
Final forms are :

आखिरी रूप हैं :

1 - विवेथ

2 - विवयिथ

वलादावार्धधातुके वेष्यते इति वार्तिकेन विकल्पेन व्यादेशः, व्यादेशाभावे आजिथ इत्यपि भवेत्।

**Comment by mrudani** [comment]
Final forms are :

अज् वस्
1 - विव्यिव

अज् मस्
विव्यिम

अत्रापि वलादावार्धधातुके वेष्यते इति विकल्पेन व्यादेशः, तदभावे आजिव, आजिम।

**Comment by drdhaval2785** [comment]
Difficult one.
