### ISSUE TITLE
अजँ लुट् 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#87]
वेता, अजिता
वेतारौ, अजितारौ
वेतारः, अजितारः
वेतासि, अजितासि
वेतास्थः, अजितास्थ
वेतास्थ, अजितास्थ
वेतास्मि, अजितास्मि
वेतास्वः, अजितास्वः
वेतास्मः, अजितास्मः

इति रूपाणि भवेयुः।

**Comment by mrudani** [comment]
यदा वी आदेशः तदा इडागमो न अनुदात्तत्वादिति न्यासकर्ता। 2-4-56

**Comment by drdhaval2785** [comment]
You are posting in Accents. Post in Verb section

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/08a2c110b9d5d472ab8f9ad5602a33eff2e20a00 closed this issue
