### ISSUE TITLE
अजँ लृट्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#88]
वेष्यति, अजिष्यति
वेष्यतः, अजिष्यतः
वेष्यन्ति, अजिष्यन्ति।
इत्येवं रीत्या सर्वेषु प्रत्ययेषु विकल्प-वि-आदेशरूपाणि ज्ञेयानि।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/commit/08a2c110b9d5d472ab8f9ad5602a33eff2e20a00 closed this issue
