### ISSUE TITLE
नखः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritAccent#9]
Input word is - नख
Please note - We have used ॑ to denote udAtta, ॒ to denote anudAtta and ᳠ to denote svarita
By khāntasyāśmādeḥ (phi-6) :
खान्तस्याश्मादेः (फि-६) :
1 - नख॑

स्वाङ्गशिटामदन्तानाम् इति सूत्रेण प्राप्तं स्वरं प्रबाध्य अनेन सूत्रेण अन्तोदात्तः इति दर्शनीयः।

**Comment by drdhaval2785** [comment]
#25 noted that we can't display such information right now.
